### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by git-eri** [chrishrb/solarlog-exporter#7]
I have a similar problem as in #3 but it seems to be with the ftp part. I used the release 0.0.3.
I tested with ftp server and with a local directory, the issue seems to be the same. What can i do do fix this?

```
solarlog_exporter  | DEBUG:urllib3.connectionpool:http://influxdb:8086 "GET /query?q=SELECT+%2A+FROM+solarlog_min+WHERE+system+%3D+%27PV-System%27+ORDER+BY+time+DESC+LIMIT+1%3B&db=solarlog HTTP/1.1" 200 None
solarlog_exporter  | WARNING:root:No last record found
solarlog_exporter  | DEBUG:root:Starting..
solarlog_exporter  | DEBUG:root:Used directory: /
solarlog_exporter  | DEBUG:root:Last Record 2023-02-25 12:52:20.456000+00:00
solarlog_exporter  | Traceback (most recent call last):
solarlog_exporter  |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
solarlog_exporter  |     return _run_code(code, main_globals, None,
solarlog_exporter  |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
solarlog_exporter  |     exec(code, run_globals)
solarlog_exporter  |   File "/app/./__main__.py", line 47, in <module>
solarlog_exporter  |     sys.exit(main())
solarlog_exporter  |   File "/app/./__main__.py", line 33, in main
solarlog_exporter  |     start_ftp_import(
solarlog_exporter  |   File "/app/./solarlog_exporter/core.py", line 89, in start_ftp_import
solarlog_exporter  |     config_parser.parse_ftp_file(ftp, path + "/base_vars.js")
solarlog_exporter  |   File "/app/./solarlog_exporter/parser.py", line 33, in parse_ftp_file
solarlog_exporter  |     ftp.retrlines(f'RETR {ftp_file_path}', string_list.append)
solarlog_exporter  |   File "/usr/local/lib/python3.8/ftplib.py", line 461, in retrlines
solarlog_exporter  |     line = fp.readline(self.maxline + 1)
solarlog_exporter  |   File "/usr/local/lib/python3.8/codecs.py", line 322, in decode
solarlog_exporter  |     (result, consumed) = self._buffer_decode(data, self.errors, final)
solarlog_exporter  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 1046: invalid start byte
```

**Comment by git-eri** [comment]
So after digging around i commented out 
```
ftp.encoding='utf-8'
ftp.sendcmd('OPTS UTF8 ON')
```
in the core.py file and i had to set the `FTP_MONITOR_FOR_CHANGES` to True.
With that i built the container using the Dockerfile and it now seems to somewhat work.
